In [2]:
import numpy as np
import pandas as pd

# Prepare data. 
Data folder must locate together
../this_py
and 
data in 
../data/data.csv
../data/label_to_category.csv

In [8]:
train = pd.read_csv("data/data.csv")
train_label_to_category = pd.read_csv("data/label_to_category.csv")

# Data Split

In [9]:
#ทำการแยก data โดยแยกตาม Label อ่านจาก csv นะจะเป็น 
# 1. label มี 100 อันและแต่ละอันบอกว่าตัวเองทำอะไรอยู่ 100 Class 
# 2. label จะใช้ในการจัดการกับข้อมูลในนี้ต่อไป

train = train.groupby('label').filter(lambda x : len(x) >= 500)
train = train.merge(train_label_to_category, on='label', how='inner')
train['category'] = train['category'].str.replace('https://upload.wikimedia.org/wikipedia/commons/Category:', '').str.lower()

In [10]:
train.head()

,landmark_id_x,url,label,landmark_id_y,category
0,0,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park
1,1,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park
2,2,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park
3,3,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park
4,4,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park

# เเสดงข้อมูล 100 Class ที่สนใจ

In [106]:
train['category'].value_counts()

enchanted_floral_gardens_of_kula                          4333
york_river_state_park                                     2627
museum_of_folk_architecture_and_ethnography_in_pyrohiv    2351
university_of_chicago_library                             2268
noraduz_cemetery                                          2248
first_landing_state_park                                  1721
flower_festival_commemorative_park                        1637
botanical_garden_jevremovac                               1539
sofiyivsky_park                                           1513
douthat_state_park                                        1509
natural_tunnel_state_park                                 1509
national_m._m._grishko_botanical_garden_(kiev)            1447
mount_rainier_national_park                               1350
niagara_falls                                             1281
grand_canyon                                              1275
cambridge_university_botanic_garden                       1248
novodevichy_cemetery_(moscow)                             1168
skole_beskids_national_nature_park                        1150
khotyn_fortress                                           1108
pilkington_library                                        1107
mathura_museum                                            1093
grayson_highlands_state_park                              1088
lok_virsa_museum,_islamabad                               1047
hayravank_monastery                                       1045
golden_gate_bridge                                        1037
mount_arapiles                                            1027
matka_canyon                                              1017
genoese_fortress_(sudak)                                   986
edinburgh_castle                                           946
qutb_minar_and_its_monuments,_delhi                        945
                                                          ...
castle_heeswijk                                            589
bakhchisaray_palace                                        584
royal_botanic_garden_edinburgh                             569
bigorski_monastery                                         569
high_bridge_trail_state_park                               568
port_of_casablanca                                         567
recoleta_cemetery                                          566
neghuts_monastery                                          564
craters_of_the_moon_national_monument                      560
west_lake                                                  553
bryce_canyon_national_park                                 547
saiful_muluk_lake                                          544
luray_caverns                                              541
ellora_caves                                               540
mason_neck_state_park                                      534
occoneechee_state_park                                     534
glasnevin_cemetery                                         533
fairy_stone_state_park                                     529
meadowlark_botanical_gardens                               526
sky_meadows_state_park                                     523
yuyuan_gardens                                             521
lake_bled                                                  520
lake_burrumbeet                                            518
rohtas_fort                                                514
john_d._rockefeller_jr._library                            511
beamish_museum                                             506
olesko_castle                                              503
tel_aviv_port                                              503
aguinaldo_shrine                                           501
sailor's_creek_battlefield_historical_state_park           500
Name: category, Length: 100, dtype: int64

In [114]:
keywords = 'mount|lake|fall|cave|canyon|park|garden|cemetery|castle|palace|monastery|museum|fort|port|tower|library|monument|shrine|church|bridge'
train_selected = train[train['category'].str.contains(keywords, regex=True) & ~train['category'].str.contains('%')]
train_selected = train_selected.reset_index(drop=True)
train_selected['category'].value_counts()

enchanted_floral_gardens_of_kula                          4333
york_river_state_park                                     2627
museum_of_folk_architecture_and_ethnography_in_pyrohiv    2351
university_of_chicago_library                             2268
noraduz_cemetery                                          2248
first_landing_state_park                                  1721
flower_festival_commemorative_park                        1637
botanical_garden_jevremovac                               1539
sofiyivsky_park                                           1513
douthat_state_park                                        1509
natural_tunnel_state_park                                 1509
national_m._m._grishko_botanical_garden_(kiev)            1447
mount_rainier_national_park                               1350
niagara_falls                                             1281
grand_canyon                                              1275
cambridge_university_botanic_garden                       1248
novodevichy_cemetery_(moscow)                             1168
skole_beskids_national_nature_park                        1150
khotyn_fortress                                           1108
pilkington_library                                        1107
mathura_museum                                            1093
grayson_highlands_state_park                              1088
lok_virsa_museum,_islamabad                               1047
hayravank_monastery                                       1045
golden_gate_bridge                                        1037
mount_arapiles                                            1027
matka_canyon                                              1017
genoese_fortress_(sudak)                                   986
edinburgh_castle                                           946
qutb_minar_and_its_monuments,_delhi                        945
                                                          ...
castle_heeswijk                                            589
bakhchisaray_palace                                        584
royal_botanic_garden_edinburgh                             569
bigorski_monastery                                         569
high_bridge_trail_state_park                               568
port_of_casablanca                                         567
recoleta_cemetery                                          566
neghuts_monastery                                          564
craters_of_the_moon_national_monument                      560
west_lake                                                  553
bryce_canyon_national_park                                 547
saiful_muluk_lake                                          544
luray_caverns                                              541
ellora_caves                                               540
mason_neck_state_park                                      534
occoneechee_state_park                                     534
glasnevin_cemetery                                         533
fairy_stone_state_park                                     529
meadowlark_botanical_gardens                               526
sky_meadows_state_park                                     523
yuyuan_gardens                                             521
lake_bled                                                  520
lake_burrumbeet                                            518
rohtas_fort                                                514
john_d._rockefeller_jr._library                            511
beamish_museum                                             506
olesko_castle                                              503
tel_aviv_port                                              503
aguinaldo_shrine                                           501
sailor's_creek_battlefield_historical_state_park           500
Name: category, Length: 100, dtype: int64

In [115]:
train_selected.head()

,landmark_id_x,url,label,landmark_id_y,category
0,0,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park
1,1,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park
2,2,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park
3,3,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park
4,4,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park

In [116]:
train_selected_label_to_category = train_selected[['landmark_id_y', 'category']].drop_duplicates()
train_selected_label_to_category = train_selected_label_to_category.reset_index(drop=True)
train_selected_label_to_category['label'] = train_selected_label_to_category.index
train_selected_label_to_category.head()

   landmark_id_y                         category  label
0         192931            york_river_state_park      0
1         186080  osaka_prefectural_flower_garden      1
2          19605                saiful_muluk_lake      2
3         171683      lok_virsa_museum,_islamabad      3
4         189811                        lake_como      4

In [119]:
train_selected = train_selected.merge(train_selected_label_to_category[['landmark_id_y', 'label']], on='landmark_id_y', how='left')
train_selected = train_selected.reset_index()
train_selected.head()

,index,landmark_id_x,url,label_x,landmark_id_y,category,label_y
0,0,0,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park,0
1,1,1,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park,0
2,2,2,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park,0
3,3,3,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park,0
4,4,4,https://upload.wikimedia.org/wikipedia/commons...,0,192931,york_river_state_park,0

In [12]:
train_selected = train_selected.drop(columns=['id', 'landmark_id', 'category'])
train_selected.head()

   index                                                url  label
0      0  https://upload.wikimedia.org/wikipedia/commons...      0
1      1  https://upload.wikimedia.org/wikipedia/commons...      0
2      2  https://upload.wikimedia.org/wikipedia/commons...      0
3      3  https://upload.wikimedia.org/wikipedia/commons...      0
4      4  https://upload.wikimedia.org/wikipedia/commons...      0

In [15]:
train_selected.to_csv('data/data.csv', index=False)
train_selected_label_to_category.to_csv('data/label_to_category.csv', index=False)